version: "3.9"

# res: React Enterprise Starter

volumes:
  res-client-node-modules:

services:
  client:
    stdin_open: true
    image: "res-client:next"
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: "./client"
    ports:
      - "8080:8080"
    volumes:
      - ./client:/usr/src/app:cached
      - res-client-node-modules:/usr/src/app/node_modules

  storybook:
    stdin_open: true
    image: "res-client:next"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: "npm run storybook -- --quiet --ci"
    ports:
      - "6006:6006"
    volumes:
      - ./client:/usr/src/app:cached
      - res-client-node-modules:/usr/src/app/node_modules
