version: "3.9"

# tu: Temporal Uplift

volumes:
  tu-client-node-modules:

services:
  client:
    stdin_open: true
    image: "tu-client:next"
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: "./client"
    ports:
      - "8080:8080"
    volumes:
      - ./client:/usr/src/app:cached
      - tu-client-node-modules:/usr/src/app/node_modules
